# Generated by Django 3.2.6 on 2021-10-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_group_webname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='webname',
            new_name='webName',
        ),
    ]
