# Generated by Django 3.2.6 on 2021-10-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_webname_group_webname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupName',
        ),
    ]
