# Generated by Django 3.2.6 on 2021-10-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211023_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupies',
            name='dagroup',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
